---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: [--fix=auto] # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows
      - id: no-commit-to-branch
        args: [--branch, main]

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.8.0b3
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        args: [--write]

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: shellcheck
    # args: ["--enable require-variable-braces,deprecate-which"]
