---
- name: Populate service facts
  ansible.builtin.service_facts:
- name: Include iptables-legacy tasks
  ansible.builtin.include_tasks:
    file: iptables-legacy.yml
    apply:
      tags: iptables-legacy,legacy
  tags: iptables-legacy,legacy

- name: Include install tasks
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags: iptables-install,install
  tags: iptables-install,install
  when: iptables_docker_uninstall is false

- name: Include uninstall tasks
  ansible.builtin.include_tasks:
    file: uninstall.yml
    apply:
      tags: uninstall-install,uninstall
  tags: uninstall-install,uninstall
  when: iptables_docker_uninstall is true
